name: recorder
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.11+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.19.1
  mask_text_input_formatter: ^1.0.6
  percent_indicator: ^2.1.9+1
  http: ^0.12.0
  shared_preferences: ^0.5.7
  dio: ^3.0.9
  provider: ^5.0.0
  in_app_purchase: ^0.3.5+1
  audioplayers: 0.17.0
  path_provider: ^1.6.22
  rxdart: ^0.25.0
  image_picker: ^0.6.7+17
  sqflite: any
  connectivity: ^0.4.2
  url_launcher: ^6.0.3
  flutter_audio_recorder2: ^0.0.2
  equatable: ^2.0.3

  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: TT
     fonts:
        - asset: assets/fonts/TT-Regular.ttf
   - family: TTmedium
     fonts:
        - asset: assets/fonts/TT-Medium.ttf     
          
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
